
extern struct _FcGL_t s_fcGL;

#define glCullFace s_fcGL.m_glCullFace
#define glCullFace s_fcGL.m_glCullFace
#define glFrontFace s_fcGL.m_glFrontFace
#define glHint s_fcGL.m_glHint
#define glLineWidth s_fcGL.m_glLineWidth
#define glPointSize s_fcGL.m_glPointSize
#define glPolygonMode s_fcGL.m_glPolygonMode
#define glScissor s_fcGL.m_glScissor
#define glTexParameterf s_fcGL.m_glTexParameterf
#define glTexParameterfv s_fcGL.m_glTexParameterfv
#define glTexParameteri s_fcGL.m_glTexParameteri
#define glTexParameteriv s_fcGL.m_glTexParameteriv
#define glTexImage1D s_fcGL.m_glTexImage1D
#define glTexImage2D s_fcGL.m_glTexImage2D
#define glDrawBuffer s_fcGL.m_glDrawBuffer
#define glClear s_fcGL.m_glClear
#define glClearColor s_fcGL.m_glClearColor
#define glClearStencil s_fcGL.m_glClearStencil
#define glClearDepth s_fcGL.m_glClearDepth
#define glStencilMask s_fcGL.m_glStencilMask
#define glColorMask s_fcGL.m_glColorMask
#define glDepthMask s_fcGL.m_glDepthMask
#define glDisable s_fcGL.m_glDisable
#define glEnable s_fcGL.m_glEnable
#define glFinish s_fcGL.m_glFinish
#define glFlush s_fcGL.m_glFlush
#define glBlendFunc s_fcGL.m_glBlendFunc
#define glLogicOp s_fcGL.m_glLogicOp
#define glStencilFunc s_fcGL.m_glStencilFunc
#define glStencilOp s_fcGL.m_glStencilOp
#define glDepthFunc s_fcGL.m_glDepthFunc
#define glPixelStoref s_fcGL.m_glPixelStoref
#define glPixelStorei s_fcGL.m_glPixelStorei
#define glReadBuffer s_fcGL.m_glReadBuffer
#define glReadPixels s_fcGL.m_glReadPixels
#define glGetBooleanv s_fcGL.m_glGetBooleanv
#define glGetDoublev s_fcGL.m_glGetDoublev
#define glGetError s_fcGL.m_glGetError
#define glGetFloatv s_fcGL.m_glGetFloatv
#define glGetIntegerv s_fcGL.m_glGetIntegerv
#define glGetString s_fcGL.m_glGetString
#define glGetTexImage s_fcGL.m_glGetTexImage
#define glGetTexParameterfv s_fcGL.m_glGetTexParameterfv
#define glGetTexParameteriv s_fcGL.m_glGetTexParameteriv
#define glGetTexLevelParameterfv s_fcGL.m_glGetTexLevelParameterfv
#define glGetTexLevelParameteriv s_fcGL.m_glGetTexLevelParameteriv
#define glIsEnabled s_fcGL.m_glIsEnabled
#define glDepthRange s_fcGL.m_glDepthRange
#define glViewport s_fcGL.m_glViewport
#define glDrawArrays s_fcGL.m_glDrawArrays
#define glDrawElements s_fcGL.m_glDrawElements
#define glGetPointerv s_fcGL.m_glGetPointerv
#define glPolygonOffset s_fcGL.m_glPolygonOffset
#define glCopyTexImage1D s_fcGL.m_glCopyTexImage1D
#define glCopyTexImage2D s_fcGL.m_glCopyTexImage2D
#define glCopyTexSubImage1D s_fcGL.m_glCopyTexSubImage1D
#define glCopyTexSubImage2D s_fcGL.m_glCopyTexSubImage2D
#define glTexSubImage1D s_fcGL.m_glTexSubImage1D
#define glTexSubImage2D s_fcGL.m_glTexSubImage2D
#define glBindTexture s_fcGL.m_glBindTexture
#define glDeleteTextures s_fcGL.m_glDeleteTextures
#define glGenTextures s_fcGL.m_glGenTextures
#define glIsTexture s_fcGL.m_glIsTexture

#define glDrawRangeElements s_fcGL.m_glDrawRangeElements
#define glTexImage3D s_fcGL.m_glTexImage3D
#define glTexSubImage3D s_fcGL.m_glTexSubImage3D
#define glCopyTexSubImage3D s_fcGL.m_glCopyTexSubImage3D

#define glActiveTexture s_fcGL.m_glActiveTexture
#define glSampleCoverage s_fcGL.m_glSampleCoverage
#define glCompressedTexImage3D s_fcGL.m_glCompressedTexImage3D
#define glCompressedTexImage2D s_fcGL.m_glCompressedTexImage2D
#define glCompressedTexImage1D s_fcGL.m_glCompressedTexImage1D
#define glCompressedTexSubImage3D s_fcGL.m_glCompressedTexSubImage3D
#define glCompressedTexSubImage2D s_fcGL.m_glCompressedTexSubImage2D
#define glCompressedTexSubImage1D s_fcGL.m_glCompressedTexSubImage1D
#define glGetCompressedTexImage s_fcGL.m_glGetCompressedTexImage


#define glBlendFuncSeparate s_fcGL.m_glBlendFuncSeparate
#define glMultiDrawArrays s_fcGL.m_glMultiDrawArrays
#define glMultiDrawElements s_fcGL.m_glMultiDrawElements
#define glPointParameterf s_fcGL.m_glPointParameterf
#define glPointParameterfv s_fcGL.m_glPointParameterfv
#define glPointParameteri s_fcGL.m_glPointParameteri
#define glPointParameteriv s_fcGL.m_glPointParameteriv
#define glBlendColor s_fcGL.m_glBlendColor
#define glBlendEquation s_fcGL.m_glBlendEquation


#define glGenQueries s_fcGL.m_glGenQueries
#define glDeleteQueries s_fcGL.m_glDeleteQueries
#define glIsQuery s_fcGL.m_glIsQuery
#define glBeginQuery s_fcGL.m_glBeginQuery
#define glEndQuery s_fcGL.m_glEndQuery
#define glGetQueryiv s_fcGL.m_glGetQueryiv
#define glGetQueryObjectiv s_fcGL.m_glGetQueryObjectiv
#define glGetQueryObjectuiv s_fcGL.m_glGetQueryObjectuiv
#define glBindBuffer s_fcGL.m_glBindBuffer
#define glDeleteBuffers s_fcGL.m_glDeleteBuffers
#define glGenBuffers s_fcGL.m_glGenBuffers
#define glIsBuffer s_fcGL.m_glIsBuffer
#define glBufferData s_fcGL.m_glBufferData
#define glBufferSubData s_fcGL.m_glBufferSubData
#define glGetBufferSubData s_fcGL.m_glGetBufferSubData
#define glMapBuffer s_fcGL.m_glMapBuffer
#define glUnmapBuffer s_fcGL.m_glUnmapBuffer
#define glGetBufferParameteriv s_fcGL.m_glGetBufferParameteriv
#define glGetBufferPointerv s_fcGL.m_glGetBufferPointerv
#define glBlendEquationSeparate s_fcGL.m_glBlendEquationSeparate
#define glDrawBuffers s_fcGL.m_glDrawBuffers
#define glStencilOpSeparate s_fcGL.m_glStencilOpSeparate
#define glStencilFuncSeparate s_fcGL.m_glStencilFuncSeparate
#define glStencilMaskSeparate s_fcGL.m_glStencilMaskSeparate
#define glAttachShader s_fcGL.m_glAttachShader
#define glBindAttribLocation s_fcGL.m_glBindAttribLocation
#define glCompileShader s_fcGL.m_glCompileShader
#define glCreateProgram s_fcGL.m_glCreateProgram
#define glCreateShader s_fcGL.m_glCreateShader
#define glDeleteProgram s_fcGL.m_glDeleteProgram
#define glDeleteShader s_fcGL.m_glDeleteShader
#define glDetachShader s_fcGL.m_glDetachShader
#define glDisableVertexAttribArray s_fcGL.m_glDisableVertexAttribArray
#define glEnableVertexAttribArray s_fcGL.m_glEnableVertexAttribArray
#define glGetActiveAttrib s_fcGL.m_glGetActiveAttrib
#define glGetActiveUniform s_fcGL.m_glGetActiveUniform
#define glGetAttachedShaders s_fcGL.m_glGetAttachedShaders
#define glGetAttribLocation s_fcGL.m_glGetAttribLocation
#define glGetProgramiv s_fcGL.m_glGetProgramiv
#define glGetProgramInfoLog s_fcGL.m_glGetProgramInfoLog
#define glGetShaderiv s_fcGL.m_glGetShaderiv
#define glGetShaderInfoLog s_fcGL.m_glGetShaderInfoLog
#define glGetShaderSource s_fcGL.m_glGetShaderSource
#define glGetUniformLocation s_fcGL.m_glGetUniformLocation
#define glGetUniformfv s_fcGL.m_glGetUniformfv
#define glGetUniformiv s_fcGL.m_glGetUniformiv
#define glGetVertexAttribdv s_fcGL.m_glGetVertexAttribdv
#define glGetVertexAttribfv s_fcGL.m_glGetVertexAttribfv
#define glGetVertexAttribiv s_fcGL.m_glGetVertexAttribiv
#define glGetVertexAttribPointerv s_fcGL.m_glGetVertexAttribPointerv
#define glIsProgram s_fcGL.m_glIsProgram
#define glIsShader s_fcGL.m_glIsShader
#define glLinkProgram s_fcGL.m_glLinkProgram
#define glShaderSource s_fcGL.m_glShaderSource
#define glUseProgram s_fcGL.m_glUseProgram
#define glUniform1f s_fcGL.m_glUniform1f
#define glUniform2f s_fcGL.m_glUniform2f
#define glUniform3f s_fcGL.m_glUniform3f
#define glUniform4f s_fcGL.m_glUniform4f
#define glUniform1i s_fcGL.m_glUniform1i
#define glUniform2i s_fcGL.m_glUniform2i
#define glUniform3i s_fcGL.m_glUniform3i
#define glUniform4i s_fcGL.m_glUniform4i
#define glUniform1fv s_fcGL.m_glUniform1fv
#define glUniform2fv s_fcGL.m_glUniform2fv
#define glUniform3fv s_fcGL.m_glUniform3fv
#define glUniform4fv s_fcGL.m_glUniform4fv
#define glUniform1iv s_fcGL.m_glUniform1iv
#define glUniform2iv s_fcGL.m_glUniform2iv
#define glUniform3iv s_fcGL.m_glUniform3iv
#define glUniform4iv s_fcGL.m_glUniform4iv
#define glUniformMatrix2fv s_fcGL.m_glUniformMatrix2fv
#define glUniformMatrix3fv s_fcGL.m_glUniformMatrix3fv
#define glUniformMatrix4fv s_fcGL.m_glUniformMatrix4fv
#define glValidateProgram s_fcGL.m_glValidateProgram
#define glVertexAttrib1d s_fcGL.m_glVertexAttrib1d
#define glVertexAttrib1dv s_fcGL.m_glVertexAttrib1dv
#define glVertexAttrib1f s_fcGL.m_glVertexAttrib1f
#define glVertexAttrib1fv s_fcGL.m_glVertexAttrib1fv
#define glVertexAttrib1s s_fcGL.m_glVertexAttrib1s
#define glVertexAttrib1sv s_fcGL.m_glVertexAttrib1sv
#define glVertexAttrib2d s_fcGL.m_glVertexAttrib2d
#define glVertexAttrib2dv s_fcGL.m_glVertexAttrib2dv
#define glVertexAttrib2f s_fcGL.m_glVertexAttrib2f
#define glVertexAttrib2fv s_fcGL.m_glVertexAttrib2fv
#define glVertexAttrib2s s_fcGL.m_glVertexAttrib2s
#define glVertexAttrib2sv s_fcGL.m_glVertexAttrib2sv
#define glVertexAttrib3d s_fcGL.m_glVertexAttrib3d
#define glVertexAttrib3dv s_fcGL.m_glVertexAttrib3dv
#define glVertexAttrib3f s_fcGL.m_glVertexAttrib3f
#define glVertexAttrib3fv s_fcGL.m_glVertexAttrib3fv
#define glVertexAttrib3s s_fcGL.m_glVertexAttrib3s
#define glVertexAttrib3sv s_fcGL.m_glVertexAttrib3sv
#define glVertexAttrib4Nbv s_fcGL.m_glVertexAttrib4Nbv
#define glVertexAttrib4Niv s_fcGL.m_glVertexAttrib4Niv
#define glVertexAttrib4Nsv s_fcGL.m_glVertexAttrib4Nsv
#define glVertexAttrib4Nub s_fcGL.m_glVertexAttrib4Nub
#define glVertexAttrib4Nubv s_fcGL.m_glVertexAttrib4Nubv
#define glVertexAttrib4Nuiv s_fcGL.m_glVertexAttrib4Nuiv
#define glVertexAttrib4Nusv s_fcGL.m_glVertexAttrib4Nusv
#define glVertexAttrib4bv s_fcGL.m_glVertexAttrib4bv
#define glVertexAttrib4d s_fcGL.m_glVertexAttrib4d
#define glVertexAttrib4dv s_fcGL.m_glVertexAttrib4dv
#define glVertexAttrib4f s_fcGL.m_glVertexAttrib4f
#define glVertexAttrib4fv s_fcGL.m_glVertexAttrib4fv
#define glVertexAttrib4iv s_fcGL.m_glVertexAttrib4iv
#define glVertexAttrib4s s_fcGL.m_glVertexAttrib4s
#define glVertexAttrib4sv s_fcGL.m_glVertexAttrib4sv
#define glVertexAttrib4ubv s_fcGL.m_glVertexAttrib4ubv
#define glVertexAttrib4uiv s_fcGL.m_glVertexAttrib4uiv
#define glVertexAttrib4usv s_fcGL.m_glVertexAttrib4usv
#define glVertexAttribPointer s_fcGL.m_glVertexAttribPointer
#define glBindVertexArray s_fcGL.m_glBindVertexArray
#define glDeleteVertexArrays s_fcGL.m_glDeleteVertexArrays
#define glGenVertexArrays s_fcGL.m_glGenVertexArrays
#define glIsVertexArray s_fcGL.m_glIsVertexArray
#define glBindVertexBuffer s_fcGL.m_glBindVertexBuffer
#define glVertexAttribFormat s_fcGL.m_glVertexAttribFormat
#define glVertexAttribIFormat s_fcGL.m_glVertexAttribIFormat
#define glVertexAttribLFormat s_fcGL.m_glVertexAttribLFormat
#define glVertexAttribBinding s_fcGL.m_glVertexAttribBinding
#define glVertexBindingDivisor s_fcGL.m_glVertexBindingDivisor

#define glDebugMessageControl s_fcGL.m_glDebugMessageControl
#define glDebugMessageInsert s_fcGL.m_glDebugMessageInsert
#define glDebugMessageCallback s_fcGL.m_glDebugMessageCallback
#define glGetDebugMessageLog s_fcGL.m_glGetDebugMessageLog
#define glPushDebugGroup s_fcGL.m_glPushDebugGroup
#define glPopDebugGroup s_fcGL.m_glPopDebugGroup
#define glObjectLabel s_fcGL.m_glObjectLabel
#define glGetObjectLabel s_fcGL.m_glGetObjectLabel
#define glObjectPtrLabel s_fcGL.m_glObjectPtrLabel
#define glGetObjectPtrLabel s_fcGL.m_glGetObjectPtrLabel
#define glGetUniformIndices s_fcGL.m_glGetUniformIndices
#define glGetActiveUniformsiv s_fcGL.m_glGetActiveUniformsiv
#define glGetActiveUniformName s_fcGL.m_glGetActiveUniformName
#define glGetUniformBlockIndex s_fcGL.m_glGetUniformBlockIndex
#define glGetActiveUniformBlockiv s_fcGL.m_glGetActiveUniformBlockiv
#define glGetActiveUniformBlockName s_fcGL.m_glGetActiveUniformBlockName
#define glBindBufferRange s_fcGL.m_glBindBufferRange
#define glBindBufferBase s_fcGL.m_glBindBufferBase
#define glGetIntegeri_v s_fcGL.m_glGetIntegeri_v
#define glUniformBlockBinding s_fcGL.m_glUniformBlockBinding

