

#ifdef __linux__
#ifndef FC_X11_KEYCODE_H
#define FC_X11_KEYCODE_H

#include <X11/keysym.h>

#define FC_KEYCODE_F1              XK_F1
#define FC_KEYCODE_ShiftL          XK_Shift_L
#define FC_KEYCODE_ShiftR          XK_Shift_R
#define FC_KEYCODE_CONTROLL        XK_Control_L
#define FC_KEYCODE_CONTROLR        XK_Control_R
#define FC_KEYCODE_ALTL            XK_Alt_L
#define FC_KEYCODE_ALTR            XK_Alt_R
#define FC_KEYCODE_SUPERL          XK_Super_L
#define FC_KEYCODE_SUPERR          XK_Super_R
#define FC_KEYCODE_MENU            XK_Menu
#define FC_KEYCODE_ESCAPE          XK_Escape
#define FC_KEYCODE_SEMICOLON       XK_semicolon
#define FC_KEYCODE_SPLASH          XK_slash
#define FC_KEYCODE_EQUAL           XK_equal
#define FC_KEYCODE_MINUS           XK_minus
#define FC_KEYCODE_BRACKETLEFT     XK_bracketleft
#define FC_KEYCODE_BRACKETRIGHT    XK_bracketright
#define FC_KEYCODE_COMMA           XK_comma
#define FC_KEYCODE_PERIOD          XK_period
#define FC_KEYCODE_APOSTROPHE      XK_apostrophe
#define FC_KEYCODE_BACKSLASH       XK_backslash
#define FC_KEYCODE_GRAVE           XK_grave
#define FC_KEYCODE_SPACE           XK_space
#define FC_KEYCODE_RETURN          XK_Return
#define FC_KEYCODE_KPENTER         XK_KP_Enter
#define FC_KEYCODE_BACKSPACE       XK_BackSpace
#define FC_KEYCODE_TAB             XK_Tab
#define FC_KEYCODE_PRIOR           XK_Prior
#define FC_KEYCODE_NEXT            XK_Next
#define FC_KEYCODE_END             XK_End
#define FC_KEYCODE_HOME            XK_Home
#define FC_KEYCODE_INSERT          XK_Insert
#define FC_KEYCODE_DELETE          XK_Delete
#define FC_KEYCODE_KPADD           XK_KP_Add
#define FC_KEYCODE_KPSUBSTRACT     XK_KP_Subtract
#define FC_KEYCODE_KPMULTIPLY      XK_KP_Multiply
#define FC_KEYCODE_KPDIVIDE        XK_KP_Divide
#define FC_KEYCODE_PAUSE           XK_Pause
#define FC_KEYCODE_F1              XK_F1
#define FC_KEYCODE_F2              XK_F2
#define FC_KEYCODE_F3              XK_F3
#define FC_KEYCODE_F4              XK_F4
#define FC_KEYCODE_F5              XK_F5
#define FC_KEYCODE_F6              XK_F6
#define FC_KEYCODE_F7              XK_F7
#define FC_KEYCODE_F8              XK_F8
#define FC_KEYCODE_F9              XK_F9
#define FC_KEYCODE_F10             XK_F10
#define FC_KEYCODE_F11             XK_F11
#define FC_KEYCODE_F12             XK_F12
#define FC_KEYCODE_F13             XK_F13
#define FC_KEYCODE_F14             XK_F14
#define FC_KEYCODE_F15             XK_F15
#define FC_KEYCODE_LEFT            XK_Left
#define FC_KEYCODE_RIGHT           XK_Right
#define FC_KEYCODE_UP              XK_Up
#define FC_KEYCODE_DOWN            XK_Down
#define FC_KEYCODE_KPINSERT        XK_KP_Insert
#define FC_KEYCODE_KPEND           XK_KP_End
#define FC_KEYCODE_KPDOWN          XK_KP_Down
#define FC_KEYCODE_KPPAGEDOWN      XK_KP_Page_Down
#define FC_KEYCODE_KPLEFT          XK_KP_Left
#define FC_KEYCODE_KPBEGIN         XK_KP_Begin
#define FC_KEYCODE_KPRIGHT         XK_KP_Right
#define FC_KEYCODE_KPHOME          XK_KP_Home
#define FC_KEYCODE_KPUP            XK_KP_Up
#define FC_KEYCODE_PAGEUP          XK_KP_Page_Up
#define FC_KEYCODE_a               XK_a
#define FC_KEYCODE_b               XK_b
#define FC_KEYCODE_c               XK_c
#define FC_KEYCODE_d               XK_d
#define FC_KEYCODE_e               XK_e
#define FC_KEYCODE_f               XK_f
#define FC_KEYCODE_g               XK_g
#define FC_KEYCODE_h               XK_h
#define FC_KEYCODE_i               XK_i
#define FC_KEYCODE_j               XK_j
#define FC_KEYCODE_k               XK_k
#define FC_KEYCODE_l               XK_l
#define FC_KEYCODE_m               XK_m
#define FC_KEYCODE_n               XK_n
#define FC_KEYCODE_o               XK_o
#define FC_KEYCODE_p               XK_p
#define FC_KEYCODE_q               XK_q
#define FC_KEYCODE_r               XK_r
#define FC_KEYCODE_s               XK_s
#define FC_KEYCODE_t               XK_t
#define FC_KEYCODE_u               XK_u
#define FC_KEYCODE_v               XK_v
#define FC_KEYCODE_w               XK_w
#define FC_KEYCODE_x               XK_x
#define FC_KEYCODE_y               XK_y
#define FC_KEYCODE_z               XK_z
#define FC_KEYCODE_0               XK_0
#define FC_KEYCODE_1               XK_1
#define FC_KEYCODE_2               XK_2
#define FC_KEYCODE_3               XK_3
#define FC_KEYCODE_4               XK_4
#define FC_KEYCODE_5               XK_5
#define FC_KEYCODE_6               XK_6
#define FC_KEYCODE_7               XK_7
#define FC_KEYCODE_8               XK_8
#define FC_KEYCODE_9               XK_9
#endif
#endif